DELETE http://localhost:3001/api/notes/60819e4689d3ba17386d5401
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwODZjMWQyZTVmYzA2MDZlMmI5NjVhNyIsInVzZXJuYW1lIjoiZm5vcnRlcyIsImlhdCI6MTYxOTY5MzU5MX0.LU_Mqsds-jw4aozpep9jdCuO0Io9ryzSNzVqaEKZi4g